# Generated by Django 4.0.4 on 2022-04-27 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('fileName', models.FileField(upload_to='files')),
                ('dateUpload', models.DateTimeField(default=datetime.datetime(2022, 4, 27, 9, 18, 45, 421848))),
            ],
        ),
    ]
