# Generated by Django 4.0.4 on 2022-04-27 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastorege', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileuploadmodel',
            name='title',
        ),
        migrations.AlterField(
            model_name='fileuploadmodel',
            name='dateUpload',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 27, 12, 13, 25, 306678)),
        ),
        migrations.AlterField(
            model_name='fileuploadmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
